pkgname = "models"
output = "./internal/models"
wipe = true
no-tests = true

[psql]
blacklist = ["schema_migrations"]
whitelist = ["orders", "outbox"]
host = "localhost"
user = "user"
pass = "pass"
port = 5432
dbname = "orders"
sslmode = "disable"
schema = "public"
